version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    container_name: shopcontainer
    image: shopimage
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning

  worker:
    build: .
    command: celery -A Core worker -l INFO
    depends_on:
      - redis
      - web

  db:
    image: postgres:13
    volumes:
     - postgres_data:/var/lib/postgresql/data
    environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
#  master:
#    image: locustio/locust
#    ports:
#      - "8089:8089"
#    volumes:
#      - ./locust:/mnt/locust
#    command: -f /mnt/locust/locustfile.py --master -H http://web:8089

#  worker:
#    image: locustio/locust
#    volumes:
#      - ./locust:/mnt/locust
#    command: -f /mnt/locust/locustfile.py --worker --master-host master

volumes:
      postgres_data:
      smtp4dev-data: