# Generated by Django 4.0.10 on 2024-01-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('CreateDate', models.DateField(auto_now_add=True)),
                ('Is_active', models.BooleanField(default=True)),
                ('EditeDate', models.DateField(auto_now=True)),
                ('Completed', models.BooleanField(default=True)),
            ],
        ),
    ]
