# Generated by Django 4.0.10 on 2024-01-25 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="ExpireDate",
            field=models.DateField(default=datetime.date(2026, 1, 25)),
        ),
    ]
