# Generated by Django 4.0.10 on 2024-02-13 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified_alter_user_expiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ExpireDate',
            field=models.DateField(default=datetime.date(2026, 2, 13)),
        ),
    ]
