name: Django-todo-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup docker
      run: docker-compose up -d
    - name: Run test
      run: docker run web sh -c "flake8 ."
