name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Build the Docker image
      run:  docker-compose up --build
    - name: Run pytest
      run:  docker-compose exec web sh -c "pytest ."
