name: T

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build doker
      run: docker-compose up -d
    - name: Run test
      run: docker exec web sh -c "pytest ."
  
