name: django todo test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build doker
      run: docker-compose up
    - name: Run test
      run: docker-compose exec web sh -c "pytest ."
  
